package br.com.lalsberg.coffee;
/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'lalsberg' at '3/12/16 11:03 AM' with Gradle 2.11
 *
 * @author lalsberg, @date 3/12/16 11:03 AM
 */
public class Library {
	public static void main(String[] args) {
		System.out.println("started");
	}
    public boolean someLibraryMethod() {
        return true;
    }
}
